### ISSUE TITLE
Field not generating custom length

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#3]
If I create a field, for example declat (for latitude). I create this as a VARCHAR, Date Length/Values=Other, and Other as 20. It looks fine until I compile and look at the generated install.mysql.utf8.sql, which shows
	`declat` VARCHAR NOT NULL DEFAULT '',

Where it should be
	`declat` VARCHAR(20) NOT NULL DEFAULT '',

**Comment by Llewellynvdm** [comment]
To get that result you must set the field called **Data Length/Values** to either 50 or 11 since there is no 20 available at this point, also set **Data Default** to none.

**Comment by mwweb** [comment]
OK, so the Other field for data length doesn't work at this point.

**Comment by Llewellynvdm** [comment]
The other in  **Data Default** is not for data length/size but for default value if the field is empty.

**Comment by Llewellynvdm** [comment]
O my I see what you mean, let me take a closer look... sorry I did not realize you were referring to other in **Data Length/Values** let me quickly test this again. one moment.

**Comment by Llewellynvdm** [comment]
Okay I found the issue, it has been fixed and should work in the future.

**Comment by Llewellynvdm** [comment]
Heads-up for the next commit.

**Comment by Llewellynvdm** [comment]
Please download the the [master branch](https://github.com/vdm-io/Joomla-Component-Builder/archive/master.zip) and simply install to update your version.

**Comment by mwweb** [comment]
Something must not be pushed completely, or simply downloading, then uploading the master branch didn't update it correctly. I downloaded, then installed, the updated version, but on compile it is still not adding the custom length (i.e. it's still creating VARCHAR rather than VARCHAR(20)

**Comment by Llewellynvdm** [comment]
Hmmm I must say that I tested it and it worked just fine.  I then at your request made double sure, and it still worked. Here are the [lines that was updated](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L4648) and they are most certainly on gitHub.

What you can do is make sure that  **Data Length/Values** is set to _Other_ and the field called _Other_ is set to 20.

What is also important to note is that to insure the field is updated in the Database you must uninstall the component you are working on and then reinstall it. 

Checking the compiled install.mysql.utf8.sql should reflect the change.

So please confirm the administrator/components/com_componentbuilder/helpers/compiler/e_Interpretation.php is the same as [the file on github](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/helpers/compiler/e_Interpretation.php#L4648) .

**Comment by Llewellynvdm** [comment]
O yes and refresh the page if the text field does not show, nothing was changed that side of the component. The component has to sides really. The UI and the Compiler, I only made changes to the compiler side of things.

**Comment by Llewellynvdm** [comment]
I presume the issue has been resolved, let me know if not.

**Comment by mwweb** [comment]
It has been. My apologies for not respondingsooner. It had been a busy week.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
